move AzGallery commands to VM Images
MicrosoftDocs/azure-docs-powershell pull request #1627
Opened 2020-11-06 23:09 UTC by olayemio

2020-11-06 23:20 UTC, opbld30 commented
Docs Build status updates of commit _[6d94389](https://github.com/olayemio/azure-docs-powershell/commits/6d94389d58b334faf90015a1c22945a2a4723f7b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[mapping/az-groupMapping-5.0.0.json](https://github.com/olayemio/azure-docs-powershell/blob/master/mapping/az-groupMapping-5.0.0.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C6%5C7fc70164-163a-8eaa-9eed-932719a16036%5CPullRequest%5C202011062309413116-1627%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=pobJATx9Ecv%2BFJZHyFbqFDay6WUCSHzz%2FYwBVU6uiGU%3D&st=2020-11-06T23%3A15%3A06Z&se=2020-12-07T23%3A20%3A06Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/7fc70164-163a-8eaa-9eed-932719a16036?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-06 23:30 UTC, opbld31 commented
Docs Build status updates of commit _[bae0a78](https://github.com/olayemio/azure-docs-powershell/commits/bae0a780a61ed830c671b9420d83a1e07ef89855)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[mapping/az-groupMapping-1.8.0.json](https://github.com/olayemio/azure-docs-powershell/blob/master/mapping/az-groupMapping-1.8.0.json) | :white_check_mark:Succeeded | |
[mapping/az-groupMapping-2.8.0.json](https://github.com/olayemio/azure-docs-powershell/blob/master/mapping/az-groupMapping-2.8.0.json) | :white_check_mark:Succeeded | |
[mapping/az-groupMapping-3.8.0.json](https://github.com/olayemio/azure-docs-powershell/blob/master/mapping/az-groupMapping-3.8.0.json) | :white_check_mark:Succeeded | |
[mapping/az-groupMapping-4.2.0.json](https://github.com/olayemio/azure-docs-powershell/blob/master/mapping/az-groupMapping-4.2.0.json) | :white_check_mark:Succeeded | |
[mapping/az-groupMapping-4.3.0.json](https://github.com/olayemio/azure-docs-powershell/blob/master/mapping/az-groupMapping-4.3.0.json) | :white_check_mark:Succeeded | |
[mapping/az-groupMapping-4.5.0.json](https://github.com/olayemio/azure-docs-powershell/blob/master/mapping/az-groupMapping-4.5.0.json) | :white_check_mark:Succeeded | |
[mapping/az-groupMapping-4.6.0.json](https://github.com/olayemio/azure-docs-powershell/blob/master/mapping/az-groupMapping-4.6.0.json) | :white_check_mark:Succeeded | |
[mapping/az-groupMapping-4.6.1.json](https://github.com/olayemio/azure-docs-powershell/blob/master/mapping/az-groupMapping-4.6.1.json) | :white_check_mark:Succeeded | |
[mapping/az-groupMapping-4.7.0.json](https://github.com/olayemio/azure-docs-powershell/blob/master/mapping/az-groupMapping-4.7.0.json) | :white_check_mark:Succeeded | |
[mapping/az-groupMapping-4.8.0.json](https://github.com/olayemio/azure-docs-powershell/blob/master/mapping/az-groupMapping-4.8.0.json) | :white_check_mark:Succeeded | |
[mapping/az-groupMapping-5.0.0.json](https://github.com/olayemio/azure-docs-powershell/blob/master/mapping/az-groupMapping-5.0.0.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C6%5C7fc70164-163a-8eaa-9eed-932719a16036%5CPullRequest%5C202011062321165536-1627%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3VXoLG2D7K%2BtN97vWVAJvuEdMWd%2BUBJGWhSI8xkzusY%3D&st=2020-11-06T23%3A25%3A39Z&se=2020-12-07T23%3A30%3A39Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/7fc70164-163a-8eaa-9eed-932719a16036?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-07 00:51 UTC, mikefrobbins requested changes
A space has been added been the closing quote for the cmdlet name and the colon. It will need to be removed before this PR can be merged.

2020-11-07 01:59 UTC, olayemio commented
I've removed the extra spaces

2020-11-07 02:04 UTC, opbld32 commented
Docs Build status updates of commit _[369e739](https://github.com/olayemio/azure-docs-powershell/commits/369e7398e2d1287c52a69095a4ad403a553b8628)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[mapping/az-groupMapping-1.8.0.json](https://github.com/olayemio/azure-docs-powershell/blob/master/mapping/az-groupMapping-1.8.0.json) | :white_check_mark:Succeeded | |
[mapping/az-groupMapping-2.8.0.json](https://github.com/olayemio/azure-docs-powershell/blob/master/mapping/az-groupMapping-2.8.0.json) | :white_check_mark:Succeeded | |
[mapping/az-groupMapping-3.8.0.json](https://github.com/olayemio/azure-docs-powershell/blob/master/mapping/az-groupMapping-3.8.0.json) | :white_check_mark:Succeeded | |
[mapping/az-groupMapping-4.2.0.json](https://github.com/olayemio/azure-docs-powershell/blob/master/mapping/az-groupMapping-4.2.0.json) | :white_check_mark:Succeeded | |
[mapping/az-groupMapping-4.3.0.json](https://github.com/olayemio/azure-docs-powershell/blob/master/mapping/az-groupMapping-4.3.0.json) | :white_check_mark:Succeeded | |
[mapping/az-groupMapping-4.5.0.json](https://github.com/olayemio/azure-docs-powershell/blob/master/mapping/az-groupMapping-4.5.0.json) | :white_check_mark:Succeeded | |
[mapping/az-groupMapping-4.6.0.json](https://github.com/olayemio/azure-docs-powershell/blob/master/mapping/az-groupMapping-4.6.0.json) | :white_check_mark:Succeeded | |
[mapping/az-groupMapping-4.6.1.json](https://github.com/olayemio/azure-docs-powershell/blob/master/mapping/az-groupMapping-4.6.1.json) | :white_check_mark:Succeeded | |
[mapping/az-groupMapping-4.7.0.json](https://github.com/olayemio/azure-docs-powershell/blob/master/mapping/az-groupMapping-4.7.0.json) | :white_check_mark:Succeeded | |
[mapping/az-groupMapping-4.8.0.json](https://github.com/olayemio/azure-docs-powershell/blob/master/mapping/az-groupMapping-4.8.0.json) | :white_check_mark:Succeeded | |
[mapping/az-groupMapping-5.0.0.json](https://github.com/olayemio/azure-docs-powershell/blob/master/mapping/az-groupMapping-5.0.0.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C7%5C7fc70164-163a-8eaa-9eed-932719a16036%5CPullRequest%5C202011070154406323-1627%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=xRjF4iA%2BQ7QGKZ4RkN5NAdAyoMIwT6yfqxhTtF2Q0MQ%3D&st=2020-11-07T01%3A59%3A51Z&se=2020-12-08T02%3A04%3A51Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/7fc70164-163a-8eaa-9eed-932719a16036?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-07 02:14 UTC, opbld30 commented
Docs Build status updates of commit _[3f8b502](https://github.com/olayemio/azure-docs-powershell/commits/3f8b502160b26f9339775d2d079ea5b1c8e76ef8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[mapping/az-groupMapping-1.8.0.json](https://github.com/olayemio/azure-docs-powershell/blob/master/mapping/az-groupMapping-1.8.0.json) | :white_check_mark:Succeeded | |
[mapping/az-groupMapping-2.8.0.json](https://github.com/olayemio/azure-docs-powershell/blob/master/mapping/az-groupMapping-2.8.0.json) | :white_check_mark:Succeeded | |
[mapping/az-groupMapping-3.8.0.json](https://github.com/olayemio/azure-docs-powershell/blob/master/mapping/az-groupMapping-3.8.0.json) | :white_check_mark:Succeeded | |
[mapping/az-groupMapping-4.2.0.json](https://github.com/olayemio/azure-docs-powershell/blob/master/mapping/az-groupMapping-4.2.0.json) | :white_check_mark:Succeeded | |
[mapping/az-groupMapping-4.3.0.json](https://github.com/olayemio/azure-docs-powershell/blob/master/mapping/az-groupMapping-4.3.0.json) | :white_check_mark:Succeeded | |
[mapping/az-groupMapping-4.5.0.json](https://github.com/olayemio/azure-docs-powershell/blob/master/mapping/az-groupMapping-4.5.0.json) | :white_check_mark:Succeeded | |
[mapping/az-groupMapping-4.6.0.json](https://github.com/olayemio/azure-docs-powershell/blob/master/mapping/az-groupMapping-4.6.0.json) | :white_check_mark:Succeeded | |
[mapping/az-groupMapping-4.6.1.json](https://github.com/olayemio/azure-docs-powershell/blob/master/mapping/az-groupMapping-4.6.1.json) | :white_check_mark:Succeeded | |
[mapping/az-groupMapping-4.7.0.json](https://github.com/olayemio/azure-docs-powershell/blob/master/mapping/az-groupMapping-4.7.0.json) | :white_check_mark:Succeeded | |
[mapping/az-groupMapping-4.8.0.json](https://github.com/olayemio/azure-docs-powershell/blob/master/mapping/az-groupMapping-4.8.0.json) | :white_check_mark:Succeeded | |
[mapping/az-groupMapping-5.0.0.json](https://github.com/olayemio/azure-docs-powershell/blob/master/mapping/az-groupMapping-5.0.0.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C7%5C7fc70164-163a-8eaa-9eed-932719a16036%5CPullRequest%5C202011070157243098-1627%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ajuc6c%2Fs%2BLgSAceAQxB2Jf1eI2p2aeIXeSMvX1h6aGI%3D&st=2020-11-07T02%3A09%3A35Z&se=2020-12-08T02%3A14%3A35Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/7fc70164-163a-8eaa-9eed-932719a16036?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-07 14:26 UTC, mikefrobbins approved these changes
LGTM

2020-11-07 14:27 UTC, merged